Add visualization graph
C2SM/Sirocco pull request #39
Opened 2024-11-15 11:33 UTC by leclairm

Generate an svg graph from the core IR using pygraphviz and adding some interactivity with javascript

NOTE: This requires graphviz to be installed locally

2024-11-15 15:44 UTC, DropD requested changes
While testing it locally with the "small" example configuration, I noticed that the "icon_input" node in the visualization is not connected to anything. Is that supposed to be the case?

2024-11-15 19:37 UTC, leclairm commented
> While testing it locally with the "small" example configuration, I noticed that the "icon_input" node in the visualization is not connected to anything. Is that supposed to be the case?

True, I always only look at the large one. It shows the visualization is good check to have! We probably need a PR to well define which scenarios we want to test.

2024-11-15 19:40 UTC, leclairm commented on src/sirocco/svg-interactive-script.js
It's not heavily based it's 99% copied! I didn't see there was a license. Yes I should absolutely include that.

2024-11-15 19:40 UTC, leclairm commented on src/sirocco/svg-interactive-style.css
same as for the `.js` file

2024-11-15 19:44 UTC, leclairm commented on src/sirocco/svg-interactive-script.js
Oh it's actually  brand new. When I "stole" it, it was only one file in the repo. There might be even more to borrow and acknowledge, then.

2024-11-15 19:47 UTC, leclairm commented on src/sirocco/svg-interactive-script.js
> Might also be not too early now to think about what license the rest of this code should have.
True, I'm happy to receive any input for that, I'm not really used to it.

2024-11-18 09:47 UTC, DropD commented on src/sirocco/svg-interactive-script.js
I created issue #41 to add a license for the project.

2024-11-18 09:48 UTC, DropD approved these changes

2024-11-27 10:50 UTC, merged